AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - "vendor/**/*"
    - "pkg/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "()"

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 80

Metrics/ClassLength:
  Max: 220
