#!/usr/bin/env bash
set -euo pipefail

for version in 2.2.10 2.3.8 2.4.10 2.5.9 2.6.10; do
  if rbenv versions --bare | grep -qx "$version"; then
    echo "Testing Ruby $version"
    RBENV_VERSION="$version" bundle _1.17.3_ exec rake
  else
    echo "Skipping Ruby $version because it is not installed"
  fi
done
